version: '3.3'

services:
  database:
    image: postgres
    container_name: authentication_database
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pgdata:/data/postgres
    networks:
      - develop

  app1:
    build: .
    container_name: authentication
    restart: always
    environment:
      DATABASE_HOST: database
      APP_PORT: ${APP_PORT}
      DEBUG_PORT: ${DEBUG_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
    networks:
      - develop

volumes:
  pgdata:
    driver: local

networks:
  develop:
    external: true
